const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

async function commitArtifact(topic, data) {
    console.log('📦 [存储服务] 收到成果，准备写入...');
    const dir = path.join(__dirname, '../output');
    if (!fs.existsSync(dir)) fs.mkdirSync(dir);
    
    const fileName = `report-${Date.now()}.md`;
    const filePath = path.join(dir, fileName);
    const content = typeof data === 'string' ? data : JSON.stringify(data, null, 2);
    const markdown = `# AI 分析报告: ${topic}\n\n${content}\n\n---\n*Generated by OpenClaw AI*`;
    
    fs.writeFileSync(filePath, markdown);
    console.log('📝 [存储服务] 文件已保存到本地: ' + fileName);

    exec('git add . && git commit -m "🤖 自动报告: ' + topic + '" && git push', (err) => {
        if (err) console.error('❌ [存储服务] Git 提交失败:', err.message);
        else console.log('✅ [存储服务] GitHub 同步完成！');
    });
}
module.exports = { commitArtifact };
